version: '3.8'
services:

  # starts a mongo (database) server and exposes it on port 27017
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  # starts mongo-express (a web ui for mongo) and exposes it on port 8081
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    restart: on-failure:5
    
  # starts a zookeeper instance (required for kafka) and exposes it on port 2181
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
  
  # starts a kafka instance and exposes it on port 9092, connected to zookeeper for coordination
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes

  # starts a redpanda-console instance (web ui for Kafka) and exposes it on port 8082, connected to kafka on port 9092
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - 8082:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    restart: on-failure:5

